spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:postgresql://localhost:5432/vivaeventos_tickets
    username: postgres
    password: 1287985dbc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: vivaeventos
    password: vivaeventos123
    virtual-host: vivaeventos

  mail:
    host: smtp.gmail.com
    port: 587
    username: juanjo.valencia.j@gmail.com
    password: amoo wtiq aoke udmt

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true